name: DrewBrownMusic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11223a'
    - '#fbeeb8'
    - '#c1c2bc'
    - '#883a3a'
    - '#d19469'
  brandStrength: 0.7061996874399483
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
